### ISSUE TITLE
Support the web(i.e. Monaco on the web)

### ISSUE THREAD

**Issue by mundusnine** [ibilon/Highlighter#3]
- Replace node fs using [khafs](https://github.com/mundusnine/khafs)(works on web with wasmerjs wasmfs). Don't hesitate to ask for api changes so that it can be used with this.

- Add support for [monaco-editor-textmate](https://github.com/NeekSandhu/monaco-editor-textmate)

- Work in progress [drop in Monaco support](https://github.com/mundusnine/monaco-kha) (it says monaco-kha but would be easily generalizable) 

Am I missing anything ?

**Comment by ibilon** [comment]
You might be misunderstanding this library/cli, it bakes highlighting of source code into html, its whole purpose is to support highlighting on the web without using client javascript. There's no relation with monaco.

What exactly are you trying to build?

**Comment by mundusnine** [comment]
Basically, text highlighting with monaco(like in vscode). I saw that the project used vscode textmate and I will probably base it off this implementation. Will fork in the future as I see now that its out of the scope of this project.
