### ISSUE TITLE
`node bin/highlighter.js highlight` command seems to be broken

### ISSUE THREAD

**Issue by Gama11** [ibilon/Highlighter#4]
`Highlighter.new` calls `registry.loadGrammarFromPathSync()`, which no longer seems to exist in the vscode-textmate version specified in `package.json` (4.1.1). It looks like the static `patchFile()`  / `patchFolder()` functions don't go through that code path (I assume that's what's used on haxe.org?).

Sidenote: it would be nice if there was a way to use `patchFolder()` via the CLI (looks like it currently only accepts single files).

**Comment by ibilon** [comment]
I might not have tested the cli usage when I last updated the dependency,
the only practical way would be to lower it back, the latest version changed everything to an async api which is not compatible at all with this lib, unless I could somehow add some await?

**Comment by Gama11** [comment]
How are grammars loaded when haxe.org is built?

**Comment by ibilon** [comment]
Ah haxe.org still use `vscode-textmate` version `3.1.5`, well then I guess I could use that as the version here, it's not like using a more recent version will be better. Since haxe.org still works then it should still build.

**Comment by Gama11** [comment]
Yeah, I don't think it's gonna make much of a difference.

**Comment by Gama11** [comment]
Fyi, I made some changes on my fork [here](https://github.com/gama11/Highlighter) for use on haxeflixel.com / snippets.haxeflixel.com:

- changed the CLI to accept directories
- grammars / submodules built-in
- downgraded vscode-textmate (requires CI to have node <= 10, 12 seems to be too new to build the native deps)
- switched to using jsdom's `DOMParser` so the HTML doesn't need to be XML-compliant

All in all this seems a lot easier to use, on CI you just have to:

- clone the highlighter repo recursively
- run `npm install` in it
- run `bin/highlighter.js <dir-with-html-files>`

And add the CSS somewhere of course.

Maybe some of theses changes could be useful for haxe.org too. Having the submodules be part of the highlighter instead of the website repo in particular seems like it causes less problems, some of these submodules don't seem to play well with Windows for some reason ([some always show up as having changes](https://i.imgur.com/hmPGQP0.png)).

**Comment by andyli** [comment]
Node 10 reached EOL for a few months now, would you upgrade the vscode-textmate version used by highlighter?
haxe.org can't be built right now.

**Comment by ibilon** [comment]
I'll take a look.
